FROM fedora:@FEDORA_VERSION@

LABEL maintainer="Daniel Henrique Barboza <danielhb413@gmail.com>"

# Disable copr repo and libvirt/qemu install in this
# step
RUN dnf install -y dnf-plugins-core && \
#    dnf copr enable -y @kubevirt/libvirt-@LIBVIRT_VERSION@ && \
#    dnf copr enable -y @kubevirt/qemu-@QEMU_VERSION@ && \
    dnf install -y \
#      libvirt-daemon-driver-qemu-@LIBVIRT_VERSION@.fc@FEDORA_VERSION@ \
#      libvirt-client-@LIBVIRT_VERSION@.fc@FEDORA_VERSION@ \
#      libvirt-daemon-driver-storage-core-@LIBVIRT_VERSION@.fc@FEDORA_VERSION@ \
#      qemu-kvm-@QEMU_VERSION@.fc@FEDORA_VERSION@ \
      genisoimage \
      selinux-policy selinux-policy-targeted \
      nftables \
      iptables \
      augeas && \
    dnf update -y libgcrypt && \
    dnf clean all

# copy libvirt and qemu RPMs (from rpms dir) and install
# them by hand
COPY rpms/* /tmp/
RUN dnf install -y \
        /tmp/libvirt-debuginfo-*.rpm \
        /tmp/libvirt-libs-*.rpm \
        /tmp/libvirt-daemon-*.rpm \
        /tmp/libvirt-daemon-driver-qemu-*.rpm \
        /tmp/libvirt-bash-completion-*.rpm \
        /tmp/libvirt-client-*.rpm \
        /tmp/libvirt-daemon-driver-storage-*.rpm \
        /tmp/qemu-*.rpm && \
    rm -f /tmp/*.rpm

COPY augconf /augconf
RUN augtool -f /augconf

COPY libvirtd.sh /libvirtd.sh
RUN chmod a+x /libvirtd.sh

RUN for qemu in /usr/bin/qemu-system-*; do setcap CAP_NET_BIND_SERVICE=+eip $qemu; done

RUN echo "Daniel Henrique Barboza <danielhb413@gmail.com>" >/maintainer

CMD ["/libvirtd.sh"]
